/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_innowhere_jnieasy_core_impl_jni_BufferNative */

#ifndef _Included_com_innowhere_jnieasy_core_impl_jni_BufferNative
#define _Included_com_innowhere_jnieasy_core_impl_jni_BufferNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    malloc
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_malloc
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    free
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_free
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    realloc
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_realloc
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getByte
 * Signature: (JJ)B
 */
JNIEXPORT jbyte JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getByte
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getBoolean
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getBoolean
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getChar
 * Signature: (JJ)C
 */
JNIEXPORT jchar JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getChar
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getShort
 * Signature: (JJ)S
 */
JNIEXPORT jshort JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getShort
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getInt
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getInt
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getLong
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getLong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getFloat
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getFloat
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getDouble
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getDouble
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getStringLength
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getStringLength
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getStringUnicodeLength
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getStringUnicodeLength
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getBooleanArray
 * Signature: (JJ[ZII)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getBooleanArray
  (JNIEnv *, jclass, jlong, jlong, jbooleanArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getByteArray
 * Signature: (JJ[BII)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getByteArray
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getCharArray
 * Signature: (JJ[CII)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getCharArray
  (JNIEnv *, jclass, jlong, jlong, jcharArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getShortArray
 * Signature: (JJ[SII)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getShortArray
  (JNIEnv *, jclass, jlong, jlong, jshortArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getIntArray
 * Signature: (JJ[III)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getIntArray
  (JNIEnv *, jclass, jlong, jlong, jintArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getLongArray
 * Signature: (JJ[JII)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getLongArray
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getFloatArray
 * Signature: (JJ[FII)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getFloatArray
  (JNIEnv *, jclass, jlong, jlong, jfloatArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    getDoubleArray
 * Signature: (JJ[DII)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_getDoubleArray
  (JNIEnv *, jclass, jlong, jlong, jdoubleArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setByte
 * Signature: (JJB)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setByte
  (JNIEnv *, jclass, jlong, jlong, jbyte);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setBoolean
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setBoolean
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setChar
 * Signature: (JJC)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setChar
  (JNIEnv *, jclass, jlong, jlong, jchar);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setShort
 * Signature: (JJS)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setShort
  (JNIEnv *, jclass, jlong, jlong, jshort);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setInt
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setInt
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setLong
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setLong
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setFloat
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setFloat
  (JNIEnv *, jclass, jlong, jlong, jfloat);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setDouble
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setDouble
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setBooleanArray
 * Signature: (JJ[ZII)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setBooleanArray
  (JNIEnv *, jclass, jlong, jlong, jbooleanArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setByteArray
 * Signature: (JJ[BII)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setByteArray
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setCharArray
 * Signature: (JJ[CII)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setCharArray
  (JNIEnv *, jclass, jlong, jlong, jcharArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setShortArray
 * Signature: (JJ[SII)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setShortArray
  (JNIEnv *, jclass, jlong, jlong, jshortArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setIntArray
 * Signature: (JJ[III)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setIntArray
  (JNIEnv *, jclass, jlong, jlong, jintArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setLongArray
 * Signature: (JJ[JII)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setLongArray
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setFloatArray
 * Signature: (JJ[FII)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setFloatArray
  (JNIEnv *, jclass, jlong, jlong, jfloatArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    setDoubleArray
 * Signature: (JJ[DII)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_setDoubleArray
  (JNIEnv *, jclass, jlong, jlong, jdoubleArray, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_BufferNative
 * Method:    copyFrom
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_BufferNative_copyFrom
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
