/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_innowhere_jnieasy_core_impl_jni_CallbackStateManagerNative */

#ifndef _Included_com_innowhere_jnieasy_core_impl_jni_CallbackStateManagerNative
#define _Included_com_innowhere_jnieasy_core_impl_jni_CallbackStateManagerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_CallbackStateManagerNative
 * Method:    registerInDLL
 * Signature: (Ljava/lang/ref/WeakReference;II)J
 */
JNIEXPORT jlong JNICALL Java_com_innowhere_jnieasy_core_impl_jni_CallbackStateManagerNative_registerInDLL
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_CallbackStateManagerNative
 * Method:    unregisterInDLL
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_CallbackStateManagerNative_unregisterInDLL
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
