/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_innowhere_jnieasy_core_impl_jni_JNIEasyLibraryNative */

#ifndef _Included_com_innowhere_jnieasy_core_impl_jni_JNIEasyLibraryNative
#define _Included_com_innowhere_jnieasy_core_impl_jni_JNIEasyLibraryNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyLibraryNative
 * Method:    registerSelf
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyLibraryNative_registerSelf
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyLibraryNative
 * Method:    unregisterSelf
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyLibraryNative_unregisterSelf
  (JNIEnv *, jobject);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyLibraryNative
 * Method:    prepare
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyLibraryNative_prepare
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyLibraryNative
 * Method:    getCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyLibraryNative_getCode
  (JNIEnv *, jclass);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyLibraryNative
 * Method:    getLicenseId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyLibraryNative_getLicenseId
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
