/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_innowhere_jnieasy_core_impl_jni_JNIEnv */

#ifndef _Included_com_innowhere_jnieasy_core_impl_jni_JNIEnv
#define _Included_com_innowhere_jnieasy_core_impl_jni_JNIEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEnv
 * Method:    getAddressCallIntMethod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEnv_getAddressCallIntMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEnv
 * Method:    NewGlobalRef
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEnv_NewGlobalRef
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEnv
 * Method:    DeleteGlobalRef
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEnv_DeleteGlobalRef
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEnv
 * Method:    GetStringUTFChars
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEnv_GetStringUTFChars
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEnv
 * Method:    ReleaseStringUTFChars
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEnv_ReleaseStringUTFChars
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
