/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_innowhere_jnieasy_core_impl_jni_JNIEasyNative */

#ifndef _Included_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
#define _Included_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
 * Method:    getPlatformAddressSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative_getPlatformAddressSize
  (JNIEnv *, jclass);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
 * Method:    getWideCharTSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative_getWideCharTSize
  (JNIEnv *, jclass);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
 * Method:    compiledWithMSVC
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative_compiledWithMSVC
  (JNIEnv *, jclass);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
 * Method:    isMacOSX
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative_isMacOSX
  (JNIEnv *, jclass);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
 * Method:    isWindows
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative_isWindows
  (JNIEnv *, jclass);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
 * Method:    getJBooleanAlignSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative_getJBooleanAlignSize
  (JNIEnv *, jclass);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
 * Method:    getJByteAlignSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative_getJByteAlignSize
  (JNIEnv *, jclass);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
 * Method:    getJCharAlignSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative_getJCharAlignSize
  (JNIEnv *, jclass);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
 * Method:    getJShortAlignSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative_getJShortAlignSize
  (JNIEnv *, jclass);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
 * Method:    getJIntAlignSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative_getJIntAlignSize
  (JNIEnv *, jclass);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
 * Method:    getJLongAlignSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative_getJLongAlignSize
  (JNIEnv *, jclass);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
 * Method:    getJFloatAlignSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative_getJFloatAlignSize
  (JNIEnv *, jclass);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
 * Method:    getJDoubleAlignSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative_getJDoubleAlignSize
  (JNIEnv *, jclass);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_JNIEasyNative
 * Method:    testFunc
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_JNIEasyNative_testFunc
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
