/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_innowhere_jnieasy_core_impl_jni_MethodNative */

#ifndef _Included_com_innowhere_jnieasy_core_impl_jni_MethodNative
#define _Included_com_innowhere_jnieasy_core_impl_jni_MethodNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_MethodNative
 * Method:    find
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_innowhere_jnieasy_core_impl_jni_MethodNative_find
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_MethodNative
 * Method:    callVoid
 * Signature: (JIJJ)V
 */
JNIEXPORT void JNICALL Java_com_innowhere_jnieasy_core_impl_jni_MethodNative_callVoid
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_MethodNative
 * Method:    callBoolean
 * Signature: (JIJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_innowhere_jnieasy_core_impl_jni_MethodNative_callBoolean
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_MethodNative
 * Method:    callByte
 * Signature: (JIJJ)B
 */
JNIEXPORT jbyte JNICALL Java_com_innowhere_jnieasy_core_impl_jni_MethodNative_callByte
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_MethodNative
 * Method:    callChar
 * Signature: (JIJJ)C
 */
JNIEXPORT jchar JNICALL Java_com_innowhere_jnieasy_core_impl_jni_MethodNative_callChar
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_MethodNative
 * Method:    callShort
 * Signature: (JIJJ)S
 */
JNIEXPORT jshort JNICALL Java_com_innowhere_jnieasy_core_impl_jni_MethodNative_callShort
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_MethodNative
 * Method:    callInt
 * Signature: (JIJJ)I
 */
JNIEXPORT jint JNICALL Java_com_innowhere_jnieasy_core_impl_jni_MethodNative_callInt
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_MethodNative
 * Method:    callLong
 * Signature: (JIJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_innowhere_jnieasy_core_impl_jni_MethodNative_callLong
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_MethodNative
 * Method:    callFloat
 * Signature: (JIJJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_innowhere_jnieasy_core_impl_jni_MethodNative_callFloat
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     com_innowhere_jnieasy_core_impl_jni_MethodNative
 * Method:    callDouble
 * Signature: (JIJJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_innowhere_jnieasy_core_impl_jni_MethodNative_callDouble
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
